#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr  6 16:13:21 2020

@author: tg
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.signal as sig
import statistics
import os
path="/Users/tg/Documents/GitHub/project-2-tessamg18/"
os.chdir(path)



fckd = open("ckd.csv", "r", encoding='utf-8')
print(fckd)